# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7672ca69a66ad99d7dde8168f0746a08e41a596c7bce674a80f481ea2fc6cfc450f2a5a9a06bfb3cca9c63b2e96d900ae42ca79e6f0ef590ca4172e76baa58b

test:
  secret_key_base: dfcf227191fb52e7949e8988a5d4b75f4e396f54b4151c3c14f6bdbad95a019a336c62f9adbe589d7107a43a962986de49d9cf5b6563b7ddde664a635815d23b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
